name: graphologyapp
description: My graphology generator

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  kf_drawer: ^1.1.2
  sqflite: any
  path: ^1.6.4
  path_provider: any
  intl: ^0.15.7
  shared_preferences: ^0.5.7
  image_picker: ^0.6.6+1
  image_cropper: ^1.2.1
  flutter_image_compress: ^0.6.7
  share: ^0.6.4+1
  url_launcher: ^5.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/
    - images/examples/
    - images/resources/